sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - FLASK_VERSION=0.12
  - FLASK_VERSION=0.11.1
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.10.1
  - FLASK_VERSION=0.10
install:
  - pip install -q Flask==$FLASK_VERSION
  - pip install -q -r dev_requirements.txt
  - pip install coveralls
  - nvm install node
  - cd test_site/web && npm install && cd ../..
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - nosetests -vs tests --with-coverage --cover-package=flask_dstore
  - cd test_site/web && npm test && cd ../..
after_success:
  - coveralls
