sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - FLASK_VERSION=0.12
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.10
install:
  - pip install -q Flask==$FLASK_VERSION
  - pip install -q -r dev_requirements.txt
  - pip install coveralls
script:
  - nosetests -vs tests --with-coverage --cover-package=flask_dstore
after_success:
  - coveralls
