sudo: false
language: python
python:
  - 2.7
env:
  - FLASK_VERSION=0.12
  - FLASK_VERSION=0.11.1
  - FLASK_VERSION=0.11
  - FLASK_VERSION=0.10.1
  - FLASK_VERSION=0.10
  - FLASK_VERSION=0.9
install:
  - pip install -q Flask==$FLASK_VERSION
  - pip install -q -r dev_requirements.txt
script:
  - nosetests -vs tests
